#ifndef KEYBOARD_H
# define KEYBOARD_H

# include <stdint.h>

# define KEYBOARD_QUEUE_SIZE	128

# define KEYBOARD_DATA_PORT		0x60
# define KEYBOARD_STATUS_PORT	0x64
# define KEYBOARD_OUTPUT_FULL	0x01

# define KEYBOARD_SCANCODE_RELEASE	0x80
# define KEYBOARD_SCANCODE_LSHIFT	0x2a
# define KEYBOARD_SCANCODE_RSHIFT	0x36
# define KEYBOARD_SCANCODE_EXTENDED	0xe0

# define KEYBOARD_SCANCODE_LEFT		0x4b
# define KEYBOARD_SCANCODE_RIGHT	0x4d
# define KEYBOARD_SCANCODE_UP		0x48
# define KEYBOARD_SCANCODE_DOWN		0x50
# define KEYBOARD_SCANCODE_DELETE	0x53

# define KEYBOARD_SCANCODE_1		0x02
# define KEYBOARD_SCANCODE_2		0x03
# define KEYBOARD_SCANCODE_3		0x04
# define KEYBOARD_SCANCODE_4		0x05
# define KEYBOARD_SCANCODE_5		0x06
# define KEYBOARD_SCANCODE_6		0x07
# define KEYBOARD_SCANCODE_7		0x08
# define KEYBOARD_SCANCODE_8		0x09
# define KEYBOARD_SCANCODE_9		0x0a
# define KEYBOARD_SCANCODE_0		0x0b
# define KEYBOARD_SCANCODE_BACKSPACE	0x0e
# define KEYBOARD_SCANCODE_Q		0x10
# define KEYBOARD_SCANCODE_W		0x11
# define KEYBOARD_SCANCODE_E		0x12
# define KEYBOARD_SCANCODE_R		0x13
# define KEYBOARD_SCANCODE_T		0x14
# define KEYBOARD_SCANCODE_Y		0x15
# define KEYBOARD_SCANCODE_U		0x16
# define KEYBOARD_SCANCODE_I		0x17
# define KEYBOARD_SCANCODE_O		0x18
# define KEYBOARD_SCANCODE_P		0x19
# define KEYBOARD_SCANCODE_ENTER	0x1c
# define KEYBOARD_SCANCODE_A		0x1e
# define KEYBOARD_SCANCODE_S		0x1f
# define KEYBOARD_SCANCODE_D		0x20
# define KEYBOARD_SCANCODE_F		0x21
# define KEYBOARD_SCANCODE_G		0x22
# define KEYBOARD_SCANCODE_H		0x23
# define KEYBOARD_SCANCODE_J		0x24
# define KEYBOARD_SCANCODE_K		0x25
# define KEYBOARD_SCANCODE_L		0x26
# define KEYBOARD_SCANCODE_Z		0x2c
# define KEYBOARD_SCANCODE_X		0x2d
# define KEYBOARD_SCANCODE_C		0x2e
# define KEYBOARD_SCANCODE_V		0x2f
# define KEYBOARD_SCANCODE_B		0x30
# define KEYBOARD_SCANCODE_N		0x31
# define KEYBOARD_SCANCODE_M		0x32
# define KEYBOARD_SCANCODE_SPACE	0x39
# define KEYBOARD_SCANCODE_ESC		0x01
# define KEYBOARD_SCANCODE_MINUS	0x0c
# define KEYBOARD_SCANCODE_EQUAL	0x0d
# define KEYBOARD_SCANCODE_TAB		0x0f
# define KEYBOARD_SCANCODE_LBRACKET	0x1a
# define KEYBOARD_SCANCODE_RBRACKET	0x1b
# define KEYBOARD_SCANCODE_LCTRL	0x1d
# define KEYBOARD_SCANCODE_SEMICOLON	0x27
# define KEYBOARD_SCANCODE_APOSTROPHE	0x28
# define KEYBOARD_SCANCODE_GRAVE	0x29
# define KEYBOARD_SCANCODE_BACKSLASH	0x2b
# define KEYBOARD_SCANCODE_LALT		0x38
# define KEYBOARD_SCANCODE_CAPSLOCK	0x3a

# define KEYBOARD_SCANCODE_F1		0x3b
# define KEYBOARD_SCANCODE_F2		0x3c
# define KEYBOARD_SCANCODE_F3		0x3d
# define KEYBOARD_SCANCODE_F4		0x3e
# define KEYBOARD_SCANCODE_F5		0x3f
# define KEYBOARD_SCANCODE_F6		0x40
# define KEYBOARD_SCANCODE_F7		0x41
# define KEYBOARD_SCANCODE_F8		0x42
# define KEYBOARD_SCANCODE_F9		0x43
# define KEYBOARD_SCANCODE_F10		0x44
# define KEYBOARD_SCANCODE_F11		0x57
# define KEYBOARD_SCANCODE_F12		0x58

# define KEYBOARD_SCANCODE_NUMLOCK	0x45
# define KEYBOARD_SCANCODE_SCROLLLOCK	0x46
# define KEYBOARD_SCANCODE_KP7		0x47
# define KEYBOARD_SCANCODE_KP8		0x48
# define KEYBOARD_SCANCODE_KP9		0x49
# define KEYBOARD_SCANCODE_KPMINUS	0x4a
# define KEYBOARD_SCANCODE_KP4		0x4b
# define KEYBOARD_SCANCODE_KP5		0x4c
# define KEYBOARD_SCANCODE_KP6		0x4d
# define KEYBOARD_SCANCODE_KPPLUS	0x4e
# define KEYBOARD_SCANCODE_MAP_SIZE	128

# define KEYBOARD_SCANCODE_KP1		0x4f
# define KEYBOARD_SCANCODE_KP2		0x50
# define KEYBOARD_SCANCODE_KP3		0x51
# define KEYBOARD_SCANCODE_KP0		0x52
# define KEYBOARD_SCANCODE_KPDOT	0x53

# define KEYBOARD_SCANCODE_RCTRL	0x1d
# define KEYBOARD_SCANCODE_RALT		0x38

# define KEYBOARD_SCANCODE_HOME		0x47
# define KEYBOARD_SCANCODE_END		0x4f
# define KEYBOARD_SCANCODE_PAGEUP	0x49
# define KEYBOARD_SCANCODE_PAGEDOWN	0x51
# define KEYBOARD_SCANCODE_INSERT	0x52

# define KEYBOARD_SCANCODE_LWIN		0x5b
# define KEYBOARD_SCANCODE_RWIN		0x5c
# define KEYBOARD_SCANCODE_MENU		0x5d

# define KEYBOARD_KEY_LEFT		0x0100
# define KEYBOARD_KEY_RIGHT		0x0101
# define KEYBOARD_KEY_UP		0x0102
# define KEYBOARD_KEY_DOWN		0x0103
# define KEYBOARD_KEY_DELETE	0x0104

typedef uint16_t	t_keyboard_key;

typedef struct s_keyboard_queue
{
	t_keyboard_key buffer[KEYBOARD_QUEUE_SIZE];
	unsigned read_index;
	unsigned write_index;
	unsigned count;
}	t_keyboard_queue;

# include "../framebuffer/screen.h"

void	keyboard_init(void);
void	keyboard_poll(void);
int		keyboard_pop(t_keyboard_key *key);
void	keyboard_write_loop(unsigned x, unsigned y);

#endif
